"""Add Flight model

Revision ID: 09992341fadd
Revises: 239809f4bfbc
Create Date: 2026-03-05 20:55:13.293556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09992341fadd'
down_revision = '239809f4bfbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_cache')
    op.drop_table('meteogram_cache')
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.alter_column('public_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=16),
               existing_nullable=False)
        batch_op.alter_column('site_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('landing_site_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_column('max_sink')
        batch_op.drop_column('max_climb')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_trial')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trial', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_climb', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('max_sink', sa.FLOAT(), nullable=True))
        batch_op.alter_column('landing_site_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('site_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('public_id',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    op.create_table('meteogram_cache',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('lat', sa.FLOAT(), nullable=False),
    sa.Column('lon', sa.FLOAT(), nullable=False),
    sa.Column('asl', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('image_data', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_cache',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('lat_key', sa.FLOAT(), nullable=False),
    sa.Column('lon_key', sa.FLOAT(), nullable=False),
    sa.Column('site_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), server_default=sa.text("'unknown'"), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lat_key', 'lon_key')
    )
    # ### end Alembic commands ###
