"""Add social auth columns

Revision ID: 239809f4bfbc
Revises: d36cd142b4ac
Create Date: 2025-12-17 23:08:46.622805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239809f4bfbc'
down_revision = 'd36cd142b4ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('apple_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.create_unique_constraint('uq_user_apple_id', ['apple_id'])
        batch_op.create_unique_constraint('uq_user_google_id', ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_google_id', type_='unique')
        batch_op.drop_constraint('uq_user_apple_id', type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('apple_id')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
