"""Add map persistence columns to User

Revision ID: d36cd142b4ac
Revises: d8984edc6372
Create Date: 2025-12-14 21:20:37.772000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36cd142b4ac'
down_revision = 'd8984edc6372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xc_perfect_location')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('xcperfect_email_time')
        batch_op.drop_column('xcperfect_asl')
        batch_op.drop_column('xcperfect_takeoff_face')
        batch_op.drop_column('xcperfect_auto_route')
        batch_op.drop_column('xcperfect_min_km')
        batch_op.drop_column('xcperfect_lat')
        batch_op.drop_column('xcperfect_lon')
        batch_op.drop_column('xcperfect_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xcperfect_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('xcperfect_lon', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('xcperfect_lat', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('xcperfect_min_km', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('xcperfect_auto_route', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('xcperfect_takeoff_face', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('xcperfect_asl', sa.FLOAT(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('xcperfect_email_time', sa.VARCHAR(length=5), server_default=sa.text("'08:00'"), nullable=True))

    op.create_table('xc_perfect_location',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('lat', sa.FLOAT(), nullable=False),
    sa.Column('lon', sa.FLOAT(), nullable=False),
    sa.Column('asl', sa.FLOAT(), nullable=True),
    sa.Column('takeoff_face', sa.VARCHAR(length=10), nullable=True),
    sa.Column('min_km', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
