"""Add user settings columns

Revision ID: d8984edc6372
Revises: 80be26e2388a
Create Date: 2025-11-21 00:33:32.030981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8984edc6372'
down_revision = '80be26e2388a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('unit_system', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ai_prompt_style', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('flight_usage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('map_style', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('map_style')
        batch_op.drop_column('flight_usage')
        batch_op.drop_column('ai_prompt_style')
        batch_op.drop_column('unit_system')
        batch_op.drop_column('ai_language')

    # ### end Alembic commands ###
